### ISSUE TITLE
Silent failure with unsupported(?) Intel Iris Graphics

### ISSUE THREAD

**Issue by pitsianis** [JuliaGPU/Metal.jl#109]
I tried Metal.jl with my trusty late 2013 13" MacBook Pro with a 2.6 GHz Dual-Core Intel Core i5 and the built-in Intel Iris GPU with 1536 MB VRAM.

I hoped Metal would work, not necessarily faster, but apparently, it fails silently. Perhaps you should refuse to run on unsupported hardware. Can Metal support old hardware with simple code modifications? In any case, I admire your great work.

```julia
julia-1.8.5|testGPU> using Metal

julia-1.8.5|testGPU> Metal.versioninfo()
macOS 11.7.4, Darwin 21.4.0

Toolchain:
- Julia: 1.8.5
- LLVM: 13.0.1

1 device:
- Intel Iris Graphics (0 bytes allocated)

julia-1.8.5|testGPU> a = MtlArray([1])
1-element MtlVector{Int64}:
 1

julia-1.8.5|testGPU> a
1-element MtlVector{Int64}:
 1

julia-1.8.5|testGPU> a .+ 1
1-element MtlVector{Int64}:
 0
```

**Comment by maleadt** [comment]
> Can Metal support old hardware with simple code modifications?

Sadly, no. See https://github.com/JuliaGPU/Metal.jl/issues/22.


> Perhaps you should refuse to run on unsupported hardware.

The problem is that for some users it seems to work fine, or at least mostly. Since we only support M-series GPUs though we should probably emit a warning at the least.

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/Metal.jl/commit/2baf6dc6edb53beb54d969b8f8efd94346ef4585
