### ISSUE TITLE
Rename `grid` to `groups`

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/Metal.jl#116]
It's currently confusing whether the `grid` kwarg to `@metal` should indicate the total grid, or just the number of threadgroups that make up the grid. The underlying API call is https://developer.apple.com/documentation/metal/mtlcomputecommandencoder/1443138-dispatchthreadgroups?language=objc, which uses `threadgroupsPerGrid` and `threadsPerThreadgroup`, so I guess we could rename to `threads` and `groups` for brevity.

**Comment by christiangnrd** [comment]
Should #119 close this?

**Comment by maleadt** [comment]
Yep, thanks.
