### ISSUE TITLE
Errors running on M1 Max

### ISSUE THREAD

**Issue by mikesha2** [JuliaGPU/Metal.jl#14]
Having trouble getting everything running, here's the versioninfo for Julia:
<img width="363" alt="image" src="https://user-images.githubusercontent.com/32970136/170572400-86ac9e1f-597f-4021-a6dc-d28445eeaed0.png">

I installed the linked fork of GPUCompilers.jl, and tried running all three scripts in the examples folder. The following error shows up:
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/32970136/170572605-ea98ea06-42aa-4b60-b46e-d9239341c3f3.png">

Any ideas?

**Comment by maleadt** [comment]
Yeah, this is a known issue. Everything is a bit in flux right now :-) Try using https://github.com/JuliaGPU/Metal.jl/pull/13 in combination with GPUCompiler#master. I'm currently in the process of stabilizing things, and hope to release something within the next couple of weeks.

**Comment by mikesha2** [comment]
Still not working for me, but I'll keep an eye out and I appreciate the incredible work! Really excited for the future of SOCs

**Comment by maleadt** [comment]
You aren't using GPUCompiler#master, as that error has been fixed there: https://github.com/JuliaGPU/GPUCompiler.jl/blob/96569b469afee52d0fdba2cab8d158ba9932b74a/src/metal.jl#L224=
