### ISSUE TITLE
rand! with Bools sometimes fails in tests in 1.9

### ISSUE THREAD

**Issue by christiangnrd** [JuliaGPU/Metal.jl#141]
As shown in [this](https://buildkite.com/julialang/metal-dot-jl/builds/382#0186f026-4f69-4721-bb32-b911fb2eb42d) buildkite failure, rand! sometimes fails. I've encountered this before sporadically.

I'll add more info if I ever encounter this again locally.

**Comment by christiangnrd** [comment]
https://buildkite.com/julialang/metal-dot-jl/builds/396#0186f5db-bea5-4a3d-9aa1-eadbf6e7be5c

**Comment by maleadt** [comment]
I haven't seen this locally, so let's hope this was also fixed by https://github.com/JuliaGPU/Metal.jl/pull/166. Please re-open if it isn't.
