### ISSUE TITLE
Powers don't work with complex floats

### ISSUE THREAD

**Issue by dchang10** [JuliaGPU/Metal.jl#142]
Taking powers of complex floats throws an error. Example:

`MtlArray([1f0*i + 0f0im for i in 1:10]) .^ (1f0/3f0)`

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/12768908/226044136-32e32851-211f-4636-98c7-38e766c589e2.png">

Powers of regular floats work fine.

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/12768908/226044501-153891fe-e417-4700-afd6-d7779b15ba6e.png">

**Comment by maleadt** [comment]
Dup of https://github.com/JuliaGPU/Metal.jl/issues/69
