### ISSUE TITLE
Random access indexing into MtlArray views cause scalar indexing

### ISSUE THREAD

**Issue by oschulz** [JuliaGPU/Metal.jl#149]
I ran into this in the context of shuffling data for ML batches:

```julia
using Metal, Random

A = MtlArray{Float32}(undef, 18, 5000000)

A_train_view = view(A, :, 1:2500000)
A_train_copy = A[:, 1:2500000]
batch_idxs = shuffle(axes(A_train_view, 2))[1:50000]

# This is *very* slow ("Warning: Performing scalar indexing on task..."):
A_train_view[:, batch_idxs]

# This is fast:
A_train_copy[:, batch_idxs]
```

CUDA.jl doesn't seem to case whether `A_train` is a view or a copy. Since both are contiguous in memory (here), I guess Metal should (in principle) be able to handle both fine as well?

**Comment by maleadt** [comment]
> Since both are contiguous in memory (here), I guess Metal should (in principle) be able to handle both fine as well?

I guess the difference is that CuArray flattens contiguous subarrays as another CuArray, while MtlArray relies on Base wrappers so result in some SubArray incantation. Easiest is probably to make MtlArray behave similarly, although it could be useful to extend the indexing methods we're relying on here to cover contiguous SubArrays. That however often results in very complicated function signatures that take nontrivial amounts of time to insert at load time (`mul!` accounts for 50% of the CUDA.jl load time or so).
