### ISSUE TITLE
Why not support threadIdx().x, blockIdx().x, blockDim().x etc?

### ISSUE THREAD

**Issue by pitsianis** [JuliaGPU/Metal.jl#163]
I agree that 'thread_position_in_grid_1d` is straightforward, but it should be trivial also to support
```c
x = threadIdx().x + (blockIdx().x - 1) * blockDim().x;
```
as well. Why did you not do it?

**Comment by vchuravy** [comment]
If you want a portable kernel programming model check out KernelAbstractions.jl
The philosophy here in the backends is to match the underlying model

**Comment by pitsianis** [comment]
Does KernelAbstractions.jl support Metal?

**Comment by vchuravy** [comment]
Yes, https://github.com/JuliaGPU/Metal.jl/blob/main/src/MetalKernels.jl

Still need to update the docs on KernelAbstractions.jl proper
