### ISSUE TITLE
Incorrect(?) darwin version in 1.8 with `Metal.versioninfo()`

### ISSUE THREAD

**Issue by christiangnrd** [JuliaGPU/Metal.jl#179]
I just noticed that when calling `Metal.versioninfo()` with Julia 1.8.5, the Darwin version is reported as `21.5.0`, while in 1.9 it's reported as `22.4.0`. It seems like this behaviour is also found when calling `versioninfo()`. Is this intended behaviour? If not, would a pull request that makes `darwin_version()` use `uname -r` be welcome or do we want to keep the behaviour the same as that of the Julia language?

**Comment by tgymnich** [comment]
`darwin_version()` returns `Base.MACHINE`, which returns the target tripple against which Julia is built.

I'd suggest something like this to get the actual darwin kernel version:
```
function getosrelease()
    size = Ref{Csize_t}()
    err = @ccall sysctlbyname("kern.osrelease"::Cstring, C_NULL::Ptr{Cvoid}, size::Ptr{Csize_t}, C_NULL::Ptr{Cvoid}, 0::Csize_t)::Cint
    Base.systemerror("sysctlbyname", err != 0)
    osrelease = Vector{Cchar}(undef, size[])
    err = @ccall sysctlbyname("kern.osrelease"::Cstring, osrelease::Ptr{Cvoid}, size::Ptr{Csize_t}, C_NULL::Ptr{Cvoid}, 0::Csize_t)::Cint
    Base.systemerror("sysctlbyname", err != 0)
    osrelease[end] = 0
    return GC.@preserve osrelease unsafe_string(pointer(osrelease))
end
```

**Comment by maleadt** [comment]
> `darwin_version()` returns `Base.MACHINE`, which returns the target tripple against which Julia is built.

Ah, that is not what I intended to report in `versioninfo()`.
