### ISSUE TITLE
Thanks for the previous fix - had a go

### ISSUE THREAD

**Issue by clive-g-brown** [JuliaGPU/Metal.jl#18]
julia --project -e 'using Pkg; Pkg.build(); Pkg.instantiate()'
ERROR: Build path for GPUCompiler does not exist: /Users/xxx/.julia/packages/GPUCompiler/wK8OU
Stacktrace:

I then created the wK8OU directory by copying the one that is there. Its starts to compile but then I get 👍 

Building Metal → `~/Downloads/Metal.jl/deps/build.log`
Precompiling project...
  ✗ Metal
  2 dependencies successfully precompiled in 5 seconds. 19 already precompiled.
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package

Stacktrace:
 [1] macro expansion
   @ ./loading.jl:1047 [inlined]
 [2] macro expansion
   @ ./lock.jl:223 [inlined]
 [3] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1028

latest Mac Ultra - Xcode etc etc .. Julia 1.8-beta3

I can't 'using Metal' - it doesn't load.

more informative 👍 

(base) xxx@xxxmacstudio Metal.jl % julia --project -e 'import Pkg; Pkg.precompile()'            
Precompiling project...
  ✗ Metal
  0 dependencies successfully precompiled in 3 seconds. 21 already precompiled.

ERROR: The following 1 direct dependency failed to precompile:

Metal [dde4c033-4e86-420c-a63e-0dd931031962]

Failed to precompile Metal [dde4c033-4e86-420c-a63e-0dd931031962] to /Users/xxx/.julia/compiled/v1.8/Metal/jl_SWcTNK.
ERROR: LoadError: UndefVarError: MetalCompilerTarget not defined
Stacktrace:
 [1] top-level scope
   @ ~/Downloads/Metal.jl/src/compiler/gpucompiler.jl:5
 [2] include(mod::Module, _path::String)
   @ Base ./Base.jl:422
 [3] include(x::String)
   @ Metal ~/Downloads/Metal.jl/src/Metal.jl:1
 [4] top-level scope
   @ ~/Downloads/Metal.jl/src/Metal.jl:23
 [5] include
   @ ./Base.jl:422 [inlined]
 [6] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1400
 [7] top-level scope
   @ stdin:1
in expression starting at /Users/xxx/Downloads/Metal.jl/src/compiler/gpucompiler.jl:5
in expression starting at /Users/xxx/Downloads/Metal.jl/src/Metal.jl:1
in expression starting at stdin:1
Stacktrace:
 [1] pkgerror(msg::String)
   @ Pkg.Types /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/Types.jl:67
 [2] precompile(ctx::Pkg.Types.Context, pkgs::Vector{String}; internal_call::Bool, strict::Bool, warn_loaded::Bool, already_instantiated::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Pkg.API /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/API.jl:1427
 [3] precompile
   @ /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/API.jl:1060 [inlined]
 [4] #precompile#225
   @ /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/API.jl:1057 [inlined]
 [5] precompile (repeats 2 times)
   @ /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/API.jl:1057 [inlined]
 [6] top-level scope
   @ none:1

**Comment by maleadt** [comment]
> julia --project -e 'using Pkg; Pkg.build(); Pkg.instantiate()'
> ERROR: Build path for GPUCompiler does not exist: /Users/xxx/.julia/packages/GPUCompiler/wK8OU

This means something is messed up with your Julia package installation.

> I then created the wK8OU directory by copying the one that is there. Its starts to compile but then I get 👍

That's the kind of thing that messes up your Julia package installation 🙂

You really shouldn't have to do anything other than the instructions in the README. If you're not familiar with using packages that are in development like that, I suggest you wait until there is a release.

**Comment by clive-g-brown** [comment]
ill delete it all and start from scratch.
