### ISSUE TITLE
how to set up Project.toml

### ISSUE THREAD

**Issue by WilliamSoCreat** [JuliaGPU/Metal.jl#185]
> ERROR: LoadError: could not find project file (Project.toml or JuliaProject.toml) in package at `/Users` maybe `subdir` needs to be specified

i copy one example file and  Project.toml file to one folder but still error 
whats the problem?

**Comment by WilliamSoCreat** [comment]
but i directly git clone metal.jl that i can run example

**Comment by maleadt** [comment]
The README has a quickstart on how to use this package: https://github.com/JuliaGPU/Metal.jl#quick-start

Please use Discourse or the Slack helpdesk channel for general Julia questions; the issue tracker here is only for reporting bugs.
