### ISSUE TITLE
allowscalar equivalent for Metal.jl

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGPU/Metal.jl#206]
CUDA.jl and AMDGPU.jl expose an `allowscalar(false)` interface. Is there an equivalent for Metal?

**Comment by maleadt** [comment]
As Metal is based on GPUArrays, it supports exactly the same mechanisms, yes.

**Comment by CarloLucibello** [comment]
ops, since I couldn't autocomplete it I assumed it wasn't there, sorry for the noise
