### ISSUE TITLE
KernelAbstractions: add Atomix back-end

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/Metal.jl#218]
See https://github.com/JuliaConcurrent/Atomix.jl/tree/main/lib/AtomixCUDA and https://github.com/JuliaGPU/CUDA.jl/pull/1790

**Comment by OsKnoth** [comment]
Is there any hope that we will have @atomic for Metal via KernelAbstractions

**Comment by anicusan** [comment]
I created a pull request [for this](https://github.com/JuliaConcurrent/Atomix.jl/pull/39)

**Comment by christiangnrd** [comment]
This is on the way (https://github.com/JuliaConcurrent/Atomix.jl/pull/42) with Atomix 1.0 so I think we can close this.

**Comment by efaulhaber** [comment]
What is the current status on this? My kernels with `Atomix.@atomic` are not running on Metal. Am I doing something wrong or is this not supported yet?

**Comment by christiangnrd** [comment]
Can you provide the output of `Metal.versioninfo()` in the envirnment you're trying to get it to work?

**Comment by efaulhaber** [comment]
Your comment sounded like it should be possible, so I cleaned up and updated all my dependent environments and now it works. Thanks!
