### ISSUE TITLE
Reductions don't work on Shared Arrays

### ISSUE THREAD

**Issue by tgymnich** [JuliaGPU/Metal.jl#312]
```julia
using Metal

a = mtl(rand(10_240_000), storage=Shared)
```

```sh
julia> sum(a)
0.0f0`
```

The issue might be caused by #305 

==> missing sync in Base.unsafe_convert(::Type{Ptr{S}}, x::MtlArray{T}) where {S, T}

**Comment by maleadt** [comment]
Might be good to add a CI job using another default memory type, like in CUDA.jl: https://github.com/JuliaGPU/CUDA.jl/blob/2783c88088cda38c9abec8969078344eb6fca510/.buildkite/pipeline.yml#L74-L100
