### ISSUE TITLE
Port the opportunistic synchronization from CUDA.jl

### ISSUE THREAD

**Issue by christiangnrd** [JuliaGPU/Metal.jl#317]
> It would probably be good to port the opportunistic synchronization from CUDA.jl

_Originally posted by @maleadt in https://github.com/JuliaGPU/Metal.jl/pull/314#discussion_r1521559352_

EDIT by maleadt: Specifically, the tracking of which stream has recently modified a buffer, and whether to synchronize or not.

**Comment by maleadt** [comment]
In addition, `copyto!` should be asynchronous when possible, e.g., when copying between MTLArrays. As suggested by @tgymnich, this could probably be done by always using the `MTLBlitCommandEncoder`.

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/Metal.jl/issues/443
