### ISSUE TITLE
Register v1.1.0

### ISSUE THREAD

**Issue by mtfishman** [JuliaGPU/Metal.jl#323]
Can you register a new version of the package? We would like to use `resize!(a::MtlVector, length)` introduced in #279.

**Comment by maleadt** [comment]
I just added Julia 1.11 support, so from my side v1.1.0 is good to go. Let's give @tgymnich and @christiangnrd a chance to chime in, as they have pending PRs they may want to have part of this release.

**Comment by tgymnich** [comment]
I'll soon have time to revisit #145 and #313. But I'd say those PRs are not urgent and don't need to be included in v1.1.0.

**Comment by christiangnrd** [comment]
I believe #320 is pretty much ready to go. If there are no objections and it passes CI, it’d be nice to have it in for 1.1. #321 is also potentially ready but it’s a big-ish PR requires more thorough review and I don’t want it to delay the release.

**Comment by maleadt** [comment]
https://github.com/JuliaRegistries/General/pull/104633
