### ISSUE TITLE
Tests failing with `GPUCompiler` v0.26.5 and `LLVM` v7.1

### ISSUE THREAD

**Issue by christiangnrd** [JuliaGPU/Metal.jl#350]
See https://buildkite.com/julialang/metal-dot-jl/builds/993.

**Comment by tgymnich** [comment]
Here is the root cause: https://github.com/JuliaGPU/llvm-downgrade/issues/4

**Comment by maleadt** [comment]
Did either of you run into this with a released version of Metal.jl? If not (i.e. if it was strictly tied to LLVM 7 which the latest released Metal.jl isn't compatible with yet) we don't need to rush out a release with #354.

**Comment by christiangnrd** [comment]
I noticed it because I rebased #321 after addressing review comments and everything was failing when no change I had made should have broken so much so it was most probably tied to LLVM 7 and not in any released version.
