### ISSUE TITLE
downgrades LLVM

### ISSUE THREAD

**Issue by Roh-codeur** [JuliaGPU/Metal.jl#355]
Hi

Excellent package, thanks for putting it together. am beginning to try this out. 

Quick note, maybe you are already aware. installing Metal, downgrades LLVM among other packages

```
(BlackIce) pkg> status --outdated --m
⌅ [929cbde3] LLVM v6.6.3 (<v7.1.0): GPUCompiler, Metal
⌅ [e86c9b32] ObjectiveC v2.1.1 (<v3.0.0): Metal
⌅ [f52de702] LLVMDowngrader_jll v0.1.0+2 (<v0.2.0+1): Metal
```

ta!

**Comment by tgymnich** [comment]
We previously had issues with newer versions of LLVM.jl which have been fixed since (https://github.com/JuliaGPU/Metal.jl/issues/350). The next release should support LLVM.jl  >= v7.1.0

**Comment by Roh-codeur** [comment]
ta! I will keep an eye out for the next release
