### ISSUE TITLE
Test for min / max broadcasting issue

### ISSUE THREAD

**Issue by rkierulf** [JuliaGPU/Metal.jl#389]
I've run into an issue broadcasting min and max together over a Metal array:

```
using Metal
A = Float32[1,2,3,4,5]
B = convert(MtlArray,A)
t_start, t_end = Float32(1.0), Float32(4.0)
min.(max.((A .- t_start) ./ (t_end - t_start), zero(Float32)), one(Float32))
min.(max.((B .- t_start) ./ (t_end - t_start), zero(Float32)), one(Float32))
```

The last two lines produce different results, with the results for the CPU array A being correct and the GPU array B being incorrect. For the GPU result, it seems to produce the same results as the line below, interestingly:

``` max.((B .- t_start) ./ (t_end - t_start), one(Float32)) ```

I'm seeing this on Julia 1.10.4 with a Mac M1, and I've confirmed this issue to be the cause of this failing build: https://buildkite.com/julialang/komamri-dot-jl/builds/824 which passes for Julia 1.9, so it's possible this is a regression in Julia 1.10, but I haven't confirmed this to be the case. For our use case, we should be able to work around the issue by using a tmp array to separate the min / max broadcasts, or writing an actual kernel to do the equivalent of the failing operation.

Full version info:

```
Julia Version 1.10.4
Commit 48d4fd48430 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)
```

**Comment by tgymnich** [comment]
Seems like the custom maximum / minimum implementation for metal in[ juliagpu/GPUCompile](https://github.com/JuliaGPU/GPUCompiler.jl) is broken.

**Comment by christiangnrd** [comment]
Bisected to https://github.com/JuliaLang/julia/pull/47814.

**Comment by maleadt** [comment]
Would probably be valuable to add this as a test though.

**Comment by cncastillo** [comment]
I just noticed that this was fixed in GPUCompiler.jl. Would pushing a PR bumping its version be helpful?

**Comment by christiangnrd** [comment]
@cncastillo The minimum supported Julia version was increased to 1.10 on master/main for both repos. I assume the next GPUCompiler version will be breaking and that's why it hasn't been bumped yet.
