### ISSUE TITLE
Type piracy

### ISSUE THREAD

**Issue by christiangnrd** [JuliaGPU/Metal.jl#396]
I was running Aqua.jl tests on Metal and it returned this line. Seems like it was added to work around #26. Tests seem to pass with the line commented out. Is this line still necessary, or is there some way to change it so it is no longer type piracy?

https://github.com/JuliaGPU/Metal.jl/blob/0c4d5e7f2b53ce8bbe63e2fa605f11673a993ba3/src/device/intrinsics/memory.jl#L93

**Comment by maleadt** [comment]
Since we only support macOS 13+, we can probably remove that workaround yes.
