### ISSUE TITLE
`Shared` vs `SharedStorage` in examples/unified_memory

### ISSUE THREAD

**Issue by FredericWantiez** [JuliaGPU/Metal.jl#405]
Hi, 

Slightly confused by the API shown in `examples/unified_memory.jl`, following the doc we can create a shared memory array using something like:
```julia
arr = Metal.zeros(Float32, (16,16); storage=Metal.SharedStorage)
```
but the version released seems to be on the older version of the API, with `Metal.SharedStorage` missing:
```julia
arr = Metal.zeros(Float32, (16,16); storage=Metal.Shared)
```

Details of my setup, from a fresh install of `Metal.jl`:
```bash
macOS 14.5.0, Darwin 23.5.0

Toolchain:
- Julia: 1.10.0
- LLVM: 15.0.7

Julia packages:
- Metal.jl: 1.2.0
- LLVMDowngrader_jll: 0.3.0+1

1 device:
- Apple M1 (64.000 KiB allocated)
```

**Comment by tgymnich** [comment]
This is correct. Some API cleanup work is still pending a release.

**Comment by christiangnrd** [comment]
Link to examples folder at current version tag for anyone else encountering this for until v2 gets released. https://github.com/JuliaGPU/Metal.jl/tree/v1.2.0/examples
