### ISSUE TITLE
Support for `LinearAlgebra.kron`

### ISSUE THREAD

**Issue by ytdHuang** [JuliaGPU/Metal.jl#422]
Would it also be possible to support `kron` for `MtlArray` (just like `CUDA.jl`) ?

The current `kron` for `MtlArray` uses scalar indexing.

I think we also need the methods for applying `kron` to `Transpose{T,<:MtlArray}` and `Adjoint{T,<:MtlArray}`.

**Comment by maleadt** [comment]
Should be easy enough to port, as the CUDA.jl implementation only relies on `repeat` from GPUArrays.

However, if anybody would want to work on this, I'd advise against just copying the code here, but instead moving the existing CUDA `kron` implementation to GPUArrays.

**Comment by ytdHuang** [comment]
okay, I re-make a new PR, let's discuss in `GPUArrays.jl`
