### ISSUE TITLE
Support for multiple devices

### ISSUE THREAD

**Issue by BooBSD** [JuliaGPU/Metal.jl#44]
Hello,

Thanks for your work.
I have a question: How to change current device to AMD Radeon?

```
julia> using Metal

julia> devices()
2-element Vector{MtlDevice}:
 MtlDevice(Intel(R) UHD Graphics 630)
 MtlDevice(AMD Radeon Pro 5500M)

julia> current_device()
MtlDevice:
 name:             Intel(R) UHD Graphics 630
 lowpower:         false
 headless:         true
 removable:        false
 unified memory:   true
 registry id:      4294968893
 transfer rate:    0
```

Thank you.

**Comment by maleadt** [comment]
That's currently not implemented, as the M-series laptops only have a single GPU. See https://github.com/JuliaGPU/Metal.jl/blob/8969a9ab8149b12f1deeabb608d989272506fe01/src/state.jl#L3-L15

Not hard to implement though, basically you want:

```julia
device!(dev::MtlDevice) = task_local_storage(:MtlDevice, dev)
```
