### ISSUE TITLE
Don't run benchmarks on the master branch?

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/Metal.jl#449]
See e.g. https://github.com/JuliaGPU/Metal.jl/pull/448, which has a benchmarks report in https://github.com/JuliaGPU/Metal.jl/pull/448#pullrequestreview-2347187879, but also after getting merged in https://github.com/JuliaGPU/Metal.jl/commit/da83511095b183728e47e2adc14079f5e3c120e6#commitcomment-147569793. I don't think the latter is ever going to be looked at.

Can we disable benchmarks on the master branch, or are reference results saved there and thus should we only disable the reporting?

cc @christiangnrd

**Comment by christiangnrd** [comment]
Reference results are saved there. I opened #450.

**Comment by christiangnrd** [comment]
#450 worked
