### ISSUE TITLE
Optimally choosing threads and grid

### ISSUE THREAD

**Issue by tarmangue** [JuliaGPU/Metal.jl#54]
Thank you for your work!
Following the technical preview at:
https://juliagpu.org/post/2022-06-24-metal/
I see that a kernel is called as:
```julia
@metal threads=512 grid=2 memset_kernel(a, 42)
```
Adapting the code in that preview to my use case (dynamic programming problem in macroeconomics) works (works great), but I am wondering how one should choose threads and grid optimally. Thank you in advance.

**Comment by maleadt** [comment]
Have a look at https://developer.apple.com/documentation/metal/compute_passes/calculating_threadgroup_and_grid_sizes. You can query maxTotalThreadsPerThreadgroup from Julia, and we do that in the GPUArrays integration: https://github.com/JuliaGPU/Metal.jl/blob/caabff7625cc5f551496bdfd1214f7d25feeff10/src/gpuarrays.jl#L12-L21

**Comment by williamfgc** [comment]
Just an update for those finding this issue. As of Metal.jl v16.0.6 this worked:

```
julia> Int(kernel.pipeline.maxTotalThreadsPerThreadgroup)
1024
```
