### ISSUE TITLE
XGBoost on Metal.jl

### ISSUE THREAD

**Issue by Roh-codeur** [JuliaGPU/Metal.jl#82]
Hi 

I note that this is not the best place to ask this question. Do we know if anyone is working on porting existing libs like XGBoost using Metal.jl? Looks like XGBoost official have no plans to support Apple M1

thanks!

**Comment by maleadt** [comment]
Please don't double-post: https://discourse.julialang.org/t/xgboost-rewrite-using-metal-jl/94056
