### ISSUE TITLE
Improve use of unified memory

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/Metal.jl#86]
Our buffers are currently allocated as GPU-only buffers by choosing the Private* storage mode. That's OK given our current CUDA-style programming model where we perform explicit copies to and from the GPU, but it would be nice if we'd also properly support buffers that are shared between CPU and GPU, by selecting Shared storage mode: https://developer.apple.com/documentation/metal/resource_fundamentals/choosing_a_resource_storage_mode_for_apple_gpus. This should probably be a kwarg to the MtlArray constructor.

*Since we choose Private storage mode, I'm not sure how the unified memory examples work...

**Comment by habemus-papadum** [comment]
Hi -- this looks to be done already: https://github.com/JuliaGPU/Metal.jl/blob/7f4594827eb3be387dd12d72368fb29de59bf10a/src/array.jl#L36
(MtlBuffer defaults to private but MtlArray to Shared; kwarg exists to choose another option)

If this seems correct, lmk and I will add documentation for others (and our future-selves.)

**Comment by habemus-papadum** [comment]
I agree with that.  I will try changing the default and updating the unifiedmemory example (and the gtk example)

**Comment by jvkersch** [comment]
Just wanted to add that I stumbled across this issue when using Metal.jl through KernelAbstractions; I wanted to do some experiments with shared arrays but quickly found that the default allocator allocates arrays in private storage mode. I ended up just adding some defaults to the allocator (https://github.com/jvkersch/Metal.jl/commit/08ea259c70f245eb35b164b24c79cbd57fc463be), but as I'm neither a Julia or GPU programmer this is probably not the right approach. Still interested in seeing how this issue evolves, however!

**Comment by maleadt** [comment]
CUDA.jl has recently seen a bunch of unified memory-related improvements, https://info.juliahub.com/cuda-jl-5-1-unified-memory, we should probably backport a bunch of those here (e.g. the ability to conveniently `unsafe_wrap` a Julia `Array` to `MtlArray`, if possible).

**Comment by tgymnich** [comment]
fixed by #305

**Comment by maleadt** [comment]
There's still a couple of important improvements to make, e.g. the ability to cheaply wrap Arrays with an MtlArray and vice-versa. That should make it much easier to use Metal.jl in an existing application.

**Comment by tgymnich** [comment]
tracked also here: https://github.com/JuliaGPU/Metal.jl/issues/62
