### ISSUE TITLE
mapreduce has poor performance

### ISSUE THREAD

**Issue by alanedelman** [JuliaGPU/Metal.jl#87]
the good news is with single precision
https://github.com/mitmath/18337/blob/master/lecture1/the_dream.ipynb
works

the bad news, is `@time ` doesn't  show an improvement over my cpu even with `n=50,000,000`

**Comment by maleadt** [comment]
The main array abstraction used there is `maximum`, right? We implement that using `mapreduce`, which is currently known to perform badly: https://github.com/JuliaGPU/Metal.jl/issues/46. I haven't had the time to investigate yet.

**Comment by alanedelman** [comment]
aha, keep me posted

**Comment by maleadt** [comment]
There's been quite some changes to mapreduce already, so track the remainder of the problem in https://github.com/JuliaGPU/Metal.jl/issues/46.
